services:
  app:
    container_name: admin-gpsf-website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3003:3003"
    environment:
      NODE_ENV: production
      PORT: 3003
    restart: unless-stopped
